#
# available action/menus
# documentation available at menu.yml.example
#
---
has_changes: true
menus:
- name: File Section
  sub_menus:
  - name: Uploads
    menu_items:
    - name: FloorSheet
      path: "/files/floorsheets/new"
      database_id: 141
    - name: Sales CM
      path: "/files/sales/new"
      database_id: 142
    - name: DpA5
      path: "/files/dpa5/new"
      database_id: 143
    - name: Order
      path: "/files/orders/new"
      database_id: 144
    - name: CloseOut Debit
      path: "/files/closeouts/new?type=debit"
      database_id: 145
    - name: CloseOut Credit
      path: "/files/closeouts/new?type=credit"
      database_id: 146
    database_id: 140
  - name: Pending
    menu_items:
    - name: Pending Sales Settlement
      path: "/sales_settlements?pending=true"
      database_id: 148
    database_id: 147
  database_id: 139
- name: Account Section
  sub_menus:
  - name: Vouchers
    menu_items:
    - name: Journal
      path: "/vouchers/new"
      database_id: 151
    - name: Receipt
      path: "/vouchers/new?voucher_type=2"
      database_id: 152
    - name: Payment
      path: "/vouchers/new?voucher_type=1"
      database_id: 153
    - name: Pending Payment
      path: "/vouchers/pending_vouchers"
      database_id: 154
    database_id: 150
  - name: Ledgers
    menu_items:
    - name: Ledger List
      path: "/ledgers"
      database_id: 156
    - name: Group Member Balance Transfer
      path: "/ledgers/group_members_ledgers"
      database_id: 157
    - name: New Ledger
      request_type: :get
      path: "/ledgers/new"
      hide_on_main_navigation: true
      database_id: 158
    database_id: 155
  - name: Bills
    menu_items:
    - name: Bill List
      path: "/bills"
      database_id: 160
    - name: New Provisional Bill
      path: "/bills/new"
      database_id: 161
    - name: Deal Cancel
      path: "/share_transactions/deal_cancel"
      database_id: 162
    - name: Approve Deal Cancel
      path: "/share_transactions/pending_deal_cancel"
      database_id: 163
    database_id: 159
  - name: Bank
    menu_items:
    - name: Banks
      path: "/banks"
      database_id: 165
    - name: Bank Accounts
      path: "/bank_accounts"
      database_id: 166
    - name: Cheque Entries
      path: "/cheque_entries"
      database_id: 167
    database_id: 164
  - name: Nepse
    menu_items:
    - name: Nepse Chalan
      path: "/nepse_chalans"
      database_id: 169
    database_id: 168
  database_id: 149
- name: Client Register
  path: "/client_accounts"
  database_id: 170
- name: Employee Register
  path: "/employee_accounts"
  database_id: 171
- name: Vendor Register
  path: "/vendor_accounts"
  database_id: 172
- name: Reports
  sub_menus:
  - name: Financial Reports
    menu_items:
    - name: Balance Sheet
      path: "/report/balancesheet"
      database_id: 175
    - name: Profit & Loss
      path: "/report/profitandloss"
      database_id: 176
    - name: Trial Balance
      path: "/report/trial_balance"
      database_id: 177
    database_id: 174
  - name: Transactions / Orders
    menu_items:
    - name: Share Inventory
      path: "/share_transactions"
      database_id: 179
    - name: Orders
      path: "/orders?show=report"
      database_id: 180
    - name: Cancelled Transactions
      path: "/share_transactions?search_by=cancelled"
      database_id: 181
    database_id: 178
  - name: Settlements
    menu_items:
    - name: Receipt
      path: "/settlements?filterrific%5Bby_settlement_type%5D=receipt"
      database_id: 183
    - name: Payment
      path: "/settlements?filterrific%5Bby_settlement_type%5D=payment"
      database_id: 184
    database_id: 182
  database_id: 173
