#
# available action/menus
# documentation available at menu.yml
#
---
has_changes: true
menus:
- name: File Section
  code: FS
  sub_menus:
  - name: Uploads
    code: FS_UPL
    menu_items:
    - name: FloorSheet
      path: "/files/floorsheets/new"
      code: FS_UPL_FLS
      menu_item_id: 3
    - name: Sales CM
      path: "/files/sales/new"
      code: FS_UPL_SCM
      menu_item_id: 4
    - name: DpA5
      path: "/files/dpa5/new"
      code: FS_UPL_DPA5
      menu_item_id: 5
    - name: Order
      path: "/files/orders/new"
      code: FS_UPL_ORD
      menu_item_id: 6
    menu_item_id: 2
  - name: Pending
    code: FS_PND
    menu_items:
    - name: Pending Sales Settlement
      path: "/sales_settlements?pending=true"
      code: FS_PND_SAS
      menu_item_id: 8
    menu_item_id: 7
  menu_item_id: 1
- name: Account Section
  code: AS
  sub_menus:
  - name: Vouchers
    code: AS_VOU
    menu_items:
    - name: Journal
      path: "/vouchers/new"
      code: AS_VOU_JOU
      menu_item_id: 11
    - name: Receipt
      path: "/vouchers/new?voucher_type=2"
      code: AS_VOU_REC
      menu_item_id: 12
    - name: Payment
      path: "/vouchers/new?voucher_type=1"
      code: AS_VOU_PAY
      menu_item_id: 13
    - name: Pending Payment
      path: "/vouchers/pending_vouchers"
      code: AS_VOU_PEP
      menu_item_id: 14
    menu_item_id: 10
  - name: Ledgers
    code: AS_LED
    menu_items:
    - name: Ledger List
      path: "/ledgers"
      code: AS_LED_LEL
      menu_item_id: 16
    - name: Group Member Balance Transfer
      path: "/ledgers/group_members_ledgers"
      code: AS_LED_GMB
      menu_item_id: 17
    - name: New Ledger
      request_type: :get
      path: "/ledgers/new"
      hide_on_main_navigation: true
      code: AS_LED_NEL
      menu_item_id: 18
    menu_item_id: 15
  - name: Billing
    code: AS_BIL
    menu_items:
    - name: Bill List
      path: "/bills"
      code: AS_BIL_BIL
      menu_item_id: 20
    - name: New Provisional Bill
      path: "/bills/new"
      code: AS_BIL_NPB
      menu_item_id: 21
    - name: Deal Cancel
      path: "/share_transactions/deal_cancel"
      code: AS_BIL_DEC
      menu_item_id: 22
    - name: Approve Deal Cancel
      path: "/share_transactions/pending_deal_cancel"
      code: AS_BIL_ADC
      menu_item_id: 23
    - name: Transaction Messages
      path: "/transaction_messages"
      code: AS_BIL_TRM
      menu_item_id: 24
    - name: Payment Letters
      path: "/bank_payment_letters"
      code: AS_BIL_PMT
      menu_item_id: 25
    - name: Sales Bill Payment
      path: "/bills/sales_payment"
      code: AS_BIL_BPM
      menu_item_id: 26
    menu_item_id: 19
  - name: Bank
    code: AS_BAN
    menu_items:
    - name: Banks
      path: "/banks"
      code: AS_BAN_BAN
      menu_item_id: 28
    - name: Bank Accounts
      path: "/bank_accounts"
      code: AS_BAN_BAA
      menu_item_id: 29
    - name: Cheque Entries
      path: "/cheque_entries"
      code: AS_BAN_CHE
      menu_item_id: 30
    menu_item_id: 27
  - name: Nepse
    code: AS_NEP
    menu_items:
    - name: Nepse Chalan
      path: "/nepse_chalans"
      code: AS_NEP_NEC
      menu_item_id: 32
    menu_item_id: 31
  menu_item_id: 9
- name: Register
  code: RG
  sub_menus:
  - name: Client Register
    code: RG_CLR
    menu_items:
    - name: Clients
      path: "/client_accounts"
      code: RG_CLR_CLI
      menu_item_id: 35
    - name: Invite Clients
      path: "/client_accounts?invite=true"
      code: RG_CLR_CIN
      hide_on_main_navigation: true
      menu_item_id: 36
    menu_item_id: 34
  - name: Employee Register
    code: RG_EMR
    menu_items:
    - name: Employees
      path: "/employee_accounts"
      code: RG_EMR_EMP
      menu_item_id: 38
    - name: Edit Employee Permissions
      path: "/employee_accounts/employee_access"
      code: RG_EMR_EEP
      hide_on_main_navigation: true
      menu_item_id: 39
    menu_item_id: 37
  - name: Vendor Register
    code: RG_VER
    menu_items:
    - name: Vendors
      path: "/vendor_accounts"
      code: RG_VER_VEN
      menu_item_id: 41
    menu_item_id: 40
  menu_item_id: 33
- name: Reports
  code: RS
  sub_menus:
  - name: Financial Reports
    code: RS_FIR
    menu_items:
    - name: Balance Sheet
      path: "/report/balancesheet"
      code: RS_FIR_BAS
      menu_item_id: 44
    - name: Profit & Loss
      path: "/report/profitandloss"
      code: RS_FIR_PNL
      menu_item_id: 45
    - name: Trial Balance
      path: "/report/trial_balance"
      code: RS_FIR_TRB
      menu_item_id: 46
    menu_item_id: 43
  - name: Transactions / Orders
    code: RS_TRO
    menu_items:
    - name: Share Inventory
      path: "/share_transactions"
      code: RS_TRO_SHI
      menu_item_id: 48
    - name: Orders
      path: "/orders?show=report"
      code: RS_TRO_ORD
      menu_item_id: 49
    - name: Cancelled Transactions
      path: "/share_transactions?filterrific%5Bby_transaction_cancel_status%5D=deal_cancel_complete"
      code: RS_TRO_CAT
      menu_item_id: 50
    menu_item_id: 47
  - name: Settlements
    code: RS_SET
    menu_items:
    - name: Receipt
      path: "/settlements?filterrific%5Bby_settlement_type%5D=receipt"
      code: RS_SET_REC
      menu_item_id: 52
    - name: Payment
      path: "/settlements?filterrific%5Bby_settlement_type%5D=payment"
      code: RS_SET_PAY
      menu_item_id: 53
    - name: All
      path: "/settlements"
      code: RS_SET_ALL
      menu_item_id: 54
    menu_item_id: 51
  - name: SMS
    code: RS_SMS
    menu_items:
    - name: SMS History
      path: "/sms_messages"
      code: RS_SMS_HIS
      menu_item_id: 56
    menu_item_id: 55
  menu_item_id: 42
- name: Administration
  code: ADS
  sub_menus:
  - name: Roles Management
    code: ADS_RLM
    menu_items:
    - name: View User Roles
      path: "/user_access_roles"
      code: ADS_RLM_ARP
      menu_item_id: 59
    - name: Create User Role
      path: "/user_access_roles/new"
      code: ADS_RLM_CUR
      menu_item_id: 60
    menu_item_id: 58
  menu_item_id: 57
