#
# available action/menus
# documentation available at menu.yml
#
---
has_changes: true
menus:
- name: File Section
  code: FS
  sub_menus:
  - name: Uploads
    code: FS_UPL
    menu_items:
    - name: FloorSheet
      path: "/files/floorsheets/new"
      code: FS_UPL_FLS
      menu_item_id: 66
    - name: Sales CM
      path: "/files/sales/new"
      code: FS_UPL_SCM
      menu_item_id: 67
    - name: DpA5
      path: "/files/dpa5/new"
      code: FS_UPL_DPA5
      menu_item_id: 68
    - name: Order
      path: "/files/orders/new"
      code: FS_UPL_ORD
      menu_item_id: 69
    menu_item_id: 65
  - name: Pending
    code: FS_PND
    menu_items:
    - name: Pending Sales Settlement
      path: "/sales_settlements?pending=true"
      code: FS_PND_SAS
      menu_item_id: 71
    menu_item_id: 70
  menu_item_id: 64
- name: Account Section
  code: AS
  sub_menus:
  - name: Vouchers
    code: AS_VOU
    menu_items:
    - name: Journal
      path: "/vouchers/new"
      code: AS_VOU_JOU
      menu_item_id: 74
    - name: Receipt
      path: "/vouchers/new?voucher_type=2"
      code: AS_VOU_REC
      menu_item_id: 75
    - name: Payment
      path: "/vouchers/new?voucher_type=1"
      code: AS_VOU_PAY
      menu_item_id: 76
    - name: Pending Payment
      path: "/vouchers/pending_vouchers"
      code: AS_VOU_PEP
      menu_item_id: 77
    menu_item_id: 73
  - name: Ledgers
    code: AS_LED
    menu_items:
    - name: Ledger List
      path: "/ledgers"
      code: AS_LED_LEL
      menu_item_id: 79
    - name: Group Member Balance Transfer
      path: "/ledgers/group_members_ledgers"
      code: AS_LED_GMB
      menu_item_id: 80
    - name: New Ledger
      request_type: :get
      path: "/ledgers/new"
      hide_on_main_navigation: true
      code: AS_LED_NEL
      menu_item_id: 81
    menu_item_id: 78
  - name: Billing
    code: AS_BIL
    menu_items:
    - name: Bill List
      path: "/bills"
      code: AS_BIL_BIL
      menu_item_id: 83
    - name: New Provisional Bill
      path: "/bills/new"
      code: AS_BIL_NPB
      menu_item_id: 84
    - name: Deal Cancel
      path: "/share_transactions/deal_cancel"
      code: AS_BIL_DEC
      menu_item_id: 85
    - name: Approve Deal Cancel
      path: "/share_transactions/pending_deal_cancel"
      code: AS_BIL_ADC
      menu_item_id: 86
    - name: Transaction Messages
      path: "/transaction_messages"
      code: AS_BIL_TRM
      menu_item_id: 87
    - name: Payment Letters
      path: "/bank_payment_letters"
      code: AS_BIL_PMT
      menu_item_id: 88
    - name: Sales Bill Payment
      path: "/bills/sales_payment"
      code: AS_BIL_BPM
      menu_item_id: 89
    menu_item_id: 82
  - name: Bank
    code: AS_BAN
    menu_items:
    - name: Banks
      path: "/banks"
      code: AS_BAN_BAN
      menu_item_id: 91
    - name: Bank Accounts
      path: "/bank_accounts"
      code: AS_BAN_BAA
      menu_item_id: 92
    - name: Cheque Entries
      path: "/cheque_entries"
      code: AS_BAN_CHE
      menu_item_id: 93
    menu_item_id: 90
  - name: Nepse
    code: AS_NEP
    menu_items:
    - name: Nepse Chalan
      path: "/nepse_chalans"
      code: AS_NEP_NEC
      menu_item_id: 95
    menu_item_id: 94
  menu_item_id: 72
- name: Register
  code: RG
  sub_menus:
  - name: Client Register
    code: RG_CLR
    menu_items:
    - name: Clients
      path: "/client_accounts"
      code: RG_CLR_CLI
      menu_item_id: 98
    - name: Invite Clients
      path: "/client_accounts?invite=true"
      code: RG_CLR_CIN
      hide_on_main_navigation: true
      menu_item_id: 99
    menu_item_id: 97
  - name: Employee Register
    code: RG_EMR
    menu_items:
    - name: Employees
      path: "/employee_accounts"
      code: RG_EMR_EMP
      menu_item_id: 101
    - name: Edit Employee Permissions
      path: "/employee_accounts/employee_access"
      code: RG_EMR_EEP
      hide_on_main_navigation: true
      menu_item_id: 102
    menu_item_id: 100
  - name: Vendor Register
    code: RG_VER
    menu_items:
    - name: Vendors
      path: "/vendor_accounts"
      code: RG_VER_VEN
      menu_item_id: 104
    menu_item_id: 103
  menu_item_id: 96
- name: Reports
  code: RS
  sub_menus:
  - name: Financial Reports
    code: RS_FIR
    menu_items:
    - name: Balance Sheet
      path: "/report/balancesheet"
      code: RS_FIR_BAS
      menu_item_id: 107
    - name: Profit & Loss
      path: "/report/profitandloss"
      code: RS_FIR_PNL
      menu_item_id: 108
    - name: Trial Balance
      path: "/report/trial_balance"
      code: RS_FIR_TRB
      menu_item_id: 109
    menu_item_id: 106
  - name: Transactions / Orders
    code: RS_TRO
    menu_items:
    - name: Share Inventory
      path: "/share_transactions"
      code: RS_TRO_SHI
      menu_item_id: 111
    - name: Orders
      path: "/orders?show=report"
      code: RS_TRO_ORD
      menu_item_id: 112
    - name: Cancelled Transactions
      path: "/share_transactions?filterrific%5Bby_transaction_cancel_status%5D=deal_cancel_complete"
      code: RS_TRO_CAT
      menu_item_id: 113
    menu_item_id: 110
  - name: Settlements
    code: RS_SET
    menu_items:
    - name: Receipt
      path: "/settlements?filterrific%5Bby_settlement_type%5D=receipt"
      code: RS_SET_REC
      menu_item_id: 115
    - name: Payment
      path: "/settlements?filterrific%5Bby_settlement_type%5D=payment"
      code: RS_SET_PAY
      menu_item_id: 116
    - name: All
      path: "/settlements"
      code: RS_SET_ALL
      menu_item_id: 117
    menu_item_id: 114
  - name: SMS
    code: RS_SMS
    menu_items:
    - name: SMS History
      path: "/sms_messages"
      code: RS_SMS_HIS
      menu_item_id: 119
    menu_item_id: 118
  - name: Miscellaneous
    code: RS_MIS
    menu_items:
    - name: Bill Ageing Analysis
      path: "/bills/ageing_analysis"
      code: RS_MIS_BIL
      menu_item_id: 121
    - name: Capital Gain Report
      path: "/share_transactions/capital_gain_report"
      code: RS_MIS_CAP
      menu_item_id: 122
    menu_item_id: 120
  menu_item_id: 105
- name: Administration
  code: ADS
  sub_menus:
  - name: Roles Management
    code: ADS_RLM
    menu_items:
    - name: View User Roles
      path: "/user_access_roles"
      code: ADS_RLM_ARP
      menu_item_id: 125
    - name: Create User Role
      path: "/user_access_roles/new"
      code: ADS_RLM_CUR
      menu_item_id: 126
    menu_item_id: 124
  menu_item_id: 123
