#
# available action/menus
# documentation available at menu.yml
#
---
has_changes: true
menus:
- name: File Section
  code: FS
  sub_menus:
  - name: Uploads
    code: FS_UPL
    menu_items:
    - name: FloorSheet
      path: "/files/floorsheets/new"
      code: FS_UPL_FLS
      menu_item_id: 176
    - name: Sales CM
      path: "/files/sales/new"
      code: FS_UPL_SCM
      menu_item_id: 177
    - name: DpA5
      path: "/files/dpa5/new"
      code: FS_UPL_DPA5
      menu_item_id: 178
    - name: Order
      path: "/files/orders/new"
      code: FS_UPL_ORD
      menu_item_id: 179
    - name: CloseOut Debit
      path: "/files/closeouts/new?type=debit"
      code: FS_UPL_CLD
      menu_item_id: 180
    - name: CloseOut Credit
      path: "/files/closeouts/new?type=credit"
      code: FS_UPL_CLC
      menu_item_id: 181
    menu_item_id: 175
  - name: Pending
    code: FS_PND
    menu_items:
    - name: Pending Sales Settlement
      path: "/sales_settlements?pending=true"
      code: FS_PND_SAS
      menu_item_id: 183
    menu_item_id: 182
  menu_item_id: 174
- name: Account Section
  code: AS
  sub_menus:
  - name: Vouchers
    code: AS_VOU
    menu_items:
    - name: Journal
      path: "/vouchers/new"
      code: AS_VOU_JOU
      menu_item_id: 186
    - name: Receipt
      path: "/vouchers/new?voucher_type=2"
      code: AS_VOU_REC
      menu_item_id: 187
    - name: Payment
      path: "/vouchers/new?voucher_type=1"
      code: AS_VOU_PAY
      menu_item_id: 188
    - name: Pending Payment
      path: "/vouchers/pending_vouchers"
      code: AS_VOU_PEP
      menu_item_id: 189
    menu_item_id: 185
  - name: Ledgers
    code: AS_LED
    menu_items:
    - name: Ledger List
      path: "/ledgers"
      code: AS_LED_LEL
      menu_item_id: 191
    - name: Group Member Balance Transfer
      path: "/ledgers/group_members_ledgers"
      code: AS_LED_GMB
      menu_item_id: 192
    - name: New Ledger
      request_type: :get
      path: "/ledgers/new"
      hide_on_main_navigation: true
      code: AS_LED_NEL
      menu_item_id: 193
    menu_item_id: 190
  - name: Billing
    code: AS_BIL
    menu_items:
    - name: Bill List
      path: "/bills"
      code: AS_BIL_BIL
      menu_item_id: 195
    - name: New Provisional Bill
      path: "/bills/new"
      code: AS_BIL_NPB
      menu_item_id: 196
    - name: Deal Cancel
      path: "/share_transactions/deal_cancel"
      code: AS_BIL_DEC
      menu_item_id: 197
    - name: Approve Deal Cancel
      path: "/share_transactions/pending_deal_cancel"
      code: AS_BIL_ADC
      menu_item_id: 198
    - name: Transaction Messages
      path: "/transaction_messages"
      code: AS_BIL_TRM
      menu_item_id: 199
    - name: Payment Letters
      path: "/bank_payment_letters"
      code: AS_BIL_PMT
      menu_item_id: 200
    - name: Sales Bill Payment
      path: "/bills/sales_payment"
      code: AS_BIL_BPM
      menu_item_id: 201
    menu_item_id: 194
  - name: Bank
    code: AS_BAN
    menu_items:
    - name: Banks
      path: "/banks"
      code: AS_BAN_BAN
      menu_item_id: 203
    - name: Bank Accounts
      path: "/bank_accounts"
      code: AS_BAN_BAA
      menu_item_id: 204
    - name: Cheque Entries
      path: "/cheque_entries"
      code: AS_BAN_CHE
      menu_item_id: 205
    menu_item_id: 202
  - name: Nepse
    code: AS_NEP
    menu_items:
    - name: Nepse Chalan
      path: "/nepse_chalans"
      code: AS_NEP_NEC
      menu_item_id: 207
    menu_item_id: 206
  menu_item_id: 184
- name: Register
  code: RG
  sub_menus:
  - name: Client Register
    code: RG_CLR
    menu_items:
    - name: Clients
      path: "/client_accounts"
      code: RG_CLR_CLI
      menu_item_id: 210
    menu_item_id: 209
  - name: Employee Register
    code: RG_EMR
    menu_items:
    - name: Employees
      path: "/employee_accounts"
      code: RG_EMR_EMP
      menu_item_id: 212
    - name: Edit Employee Permissions
      path: "/employee_accounts/employee_access"
      code: RG_EMR_EEP
      hide_on_main_navigation: true
      menu_item_id: 213
    menu_item_id: 211
  - name: Vendor Register
    code: RG_VER
    menu_items:
    - name: Vendors
      path: "/vendor_accounts"
      code: RG_VER_VEN
      menu_item_id: 215
    menu_item_id: 214
  menu_item_id: 208
- name: Reports
  code: RS
  sub_menus:
  - name: Financial Reports
    code: RS_FIR
    menu_items:
    - name: Balance Sheet
      path: "/report/balancesheet"
      code: RS_FIR_BAS
      menu_item_id: 218
    - name: Profit & Loss
      path: "/report/profitandloss"
      code: RS_FIR_PNL
      menu_item_id: 219
    - name: Trial Balance
      path: "/report/trial_balance"
      code: RS_FIR_TRB
      menu_item_id: 220
    menu_item_id: 217
  - name: Transactions / Orders
    code: RS_TRO
    menu_items:
    - name: Share Inventory
      path: "/share_transactions"
      code: RS_TRO_SHI
      menu_item_id: 222
    - name: Orders
      path: "/orders?show=report"
      code: RS_TRO_ORD
      menu_item_id: 223
    - name: Cancelled Transactions
      path: "/share_transactions?search_by=cancelled"
      code: RS_TRO_CAT
      menu_item_id: 224
    menu_item_id: 221
  - name: Settlements
    code: RS_SET
    menu_items:
    - name: Receipt
      path: "/settlements?filterrific%5Bby_settlement_type%5D=receipt"
      code: RS_SET_REC
      menu_item_id: 226
    - name: Payment
      path: "/settlements?filterrific%5Bby_settlement_type%5D=payment"
      code: RS_SET_PAY
      menu_item_id: 227
    menu_item_id: 225
  - name: SMS
    code: RS_SMS
    menu_items:
    - name: SMS History
      path: "/sms_messages"
      code: RS_SMS_HIS
      menu_item_id: 229
    menu_item_id: 228
  menu_item_id: 216
